@startuml
class com.pluralsight.workshop.dealership.DealershipFileManager {
# DropDownMenuSystem dropDownMenuSystem
- String inventoryFile
# void saveToFile(Vehicle)
+ String toString()
+ String getInventoryFile()
+ String setInventoryFile(String)
+ List<Vehicle> readFromFile()
}


class com.pluralsight.workshop.dealership.DealershipInventoryManager {
- DealershipFileManager df
- List<Vehicle> filterVehicles(Predicate<Vehicle>)
+ void viewByPrice(double)
+ void viewByMakeModel(String,String)
+ void viewByYear(int)
+ void viewByColor(String)
+ void viewByMileage(int)
+ void viewByType(String)
+ void displayVehicles(List<Vehicle>)
+ void addVehicle(Vehicle)
+ void removeFromFile(String)
}


class com.pluralsight.workshop.dealership.Program {
+ {static} void main(String[])
}

@enduml