@startuml
class com.pluralsight.workshop.dealership.Dealership {
- String dealershipName
- String dealershipAddress
- String dealershipPhone
+ String getDealershipName()
+ void setDealershipName(String)
+ String getDealershipAddress()
+ void setDealershipAddress(String)
+ String getDealershipPhone()
+ void setDealershipPhone(String)
+ String toString()
}


class com.pluralsight.workshop.dealership.UserInterface {
~ JFrameKeyHighlight highlight
~ UserPrompt uPrompt
~ List<UserPrompt> promptList
~ Utilities util
~ void menuLanding()
}


class com.pluralsight.workshop.dealership.DealershipFileManager {
- String FILE_PATH
~ Dealership dealership
+ void saveToFile(Vehicle)
+ List<Vehicle> readFromFile()
}


class com.pluralsight.workshop.dealership.Program {
+ {static} void main(String[])
}

@enduml